# Specify a base image.
FROM node:12-slim AS slim

# Update npm and install typescript and ts node.
RUN npm update && \
  npm i -g typescript ts-node

# Add volume for the data request.
VOLUME [ $"DATA_REQUEST_BASE_DIR" ]

# Project working directory.
WORKDIR /opt/data-archive-backend

# Run 'yarn dev' when the container starts.
CMD ["yarn", "dev"]