# Specify a base image.
FROM node:12-slim AS slim

# Update npm and install typescript and ts node.
RUN npm update && \
  npm i -g typescript ts-node

# Project working directory.
WORKDIR /opt/data-archive-backend

# Run 'yarn dev' when the container starts.
CMD ["yarn", "dev"]